name: "NPM Publish"
on:
  release:
    types:
      - published
  push:
    branches:
      - 'jcortejoso/npm-publish-org-runners'

jobs:
  npm-publish:
    runs-on: ['self-hosted', 'npm-publish']
    # Must change the job token permissions to use JWT auth
    permissions: 
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Build and publish npm package
        uses: celo-org/reusable-workflows/.github/actions/npm-publish@961f7ff97e3aa18335ac581ecdd6ab753a6daad3 # main Sept 6th 2023
        with:
          node-version: 16
          package-dir: "packages/rainbowkit-celo"
          install-dir: "."
          package-access: "public"
          akeyless-api-gateway: https://api.gateway.akeyless.celo-networks-dev.org
          akeyless-github-access-id: p-kf9vjzruht6l
          akeyless-token-path: /static-secrets/apps-tooling-circle/npm-publish-token
